### ISSUE TITLE
你好, IOS端使用之后, 报错. 请教一下什么原因

### ISSUE THREAD

**Issue by NikiLee2016** [react-native-studio/react-native-MJRefresh#10]
![image](https://user-images.githubusercontent.com/28485853/44027316-9bb974c0-9f28-11e8-80ad-dc155f2fb0e6.png)

**Comment by 2534290808** [comment]
请附上代码，谢谢

**Comment by NikiLee2016** [comment]
![image](https://user-images.githubusercontent.com/28485853/44386026-d50bf780-a553-11e8-8674-63cc0af26113.png)
主要就是这个情况, 我FlatList部分使用的react-native-ultimate-listview, 这是截取的它的部分源码. 自定义它的下拉刷新组件, 只能通过自定义refreshControl来实现, 大佬那边有办法吗? 让其能够支持refreshControl

**Comment by 2534290808** [comment]
/**
   * Render a custom scroll component, e.g. with a differently styled `RefreshControl`.
   */
  renderScrollComponent?: (props: Object) => React.Element<any>,


    const ret = React.cloneElement(
      (this.props.renderScrollComponent || this._defaultRenderScrollComponent)(
        scrollProps,
      ),
      {
        ref: this._captureScrollRef,
      },
      cells,
    );
如果renderScrollComponent不为空，则刷新效果应在renderScrollComponent里实现，否则还是按照RN官方实现，即refreshControl智能为RefreshControl组件

**Comment by 2534290808** [comment]
我的例子：
```
<FlatList
                    keyExtractor={(item)=>item}
                    data={this.state.data}
                    renderItem={({item,index}) => <Text key={index} onPress={()=>alert(111)} style={{height:100}}>{item}</Text>}
                    renderScrollComponent={props=><ScrollView
                        style={{flex:1}}
                        refreshControl={
                            <HuaWeiRefreshControl
                                ref={ref=>this._hw = ref}
                                onRefresh={this._onRefresh}
                            />
                        }
                        {...props}
                    />}
                />
```
此时的refreshControl既可以是官方RefreshControl，也可以是其他组件（须由MJRefresh包裹）

**Comment by NikiLee2016** [comment]
好的. 你的意思就是只能使用renderScrollComponent, 对吗? 如果是那样的话, 我只能fork一下react-native-ultimate-listview这个库了, 🤣

**Comment by 2534290808** [comment]
是的，你可以看一下VirtualizedList组件的源码，官方FlatList是基于VirtualizedList实现的

**Comment by NikiLee2016** [comment]
好的. 谢谢. 
顺便问一下, 你封装的ScrollView组件, 相对于原生ScrollView组件, 优化了那些方面呢?

**Comment by NikiLee2016** [comment]
👌
我使用了你桥接的SmartRefreshLayout, 效果很好. 现在准备把IOS那边也集成一下你的MjRefresh.
问题弄清楚了, 这个issue应该可以close了.
非常感谢!

**Comment by NikiLee2016** [comment]
可否加一下你的qq/微信?

**Comment by 2534290808** [comment]
lmy2534290808 微信




------------------ 原始邮件 ------------------
发件人: "Niki"<notifications@github.com>;
发送时间: 2018年8月21日(星期二) 下午5:34
收件人: "react-native-studio/react-native-MJRefresh"<react-native-MJRefresh@noreply.github.com>;
抄送: "明月刀"<2534290808@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [react-native-studio/react-native-MJRefresh] 你好, IOS端使用之后, 报错. 请教一下什么原因 (#10)




可否加一下你的qq/微信?
