### ISSUE TITLE
MJRefresh导致上拉加载不执行

### ISSUE THREAD

**Issue by geniu-vs** [react-native-studio/react-native-MJRefresh#17]
使用MJRefresh后，上拉加载的onEndReached不再调用，怎么设置onEndReachedThreshold都没用，怀疑是重写了renderScrollComponent组件后，生成新的scrollView与FlatList本身滑动事件冲突，求处理方案。

代码：
return  <FlatList
            style={[{height:px2dp(500),width:theme.screenWidth,backgroundColor:'yellow'}]}
            refreshing={false}
            keyExtractor={(item, index) => {
                return index.toString()
            }}
            renderScrollComponent={props=><ScrollView
                style={[{height:px2dp(0),backgroundColor:'green'}]}
                horizontal={false}
                showsVerticalScrollIndicator={false}
                refreshControl={
                    <LottieRefreshControl
                        ref={ref=>this.pullLayout = ref}
                        onRefresh={this.refresh}
                        {...props}
                    />
                }
            />}
            data={this.props.data}
            footerState={this.props.refreshState}
            loadState={this.props.loadState}
            // windowSize={10}
            // initialNumToRender={5}
            // updateCellsBatchingPeriod={10}
            // maxToRenderPerBatch={10}
            renderItem={this.renderRowView}
            loadMore={this.props.loadMore.bind(this)}
            ListEmptyComponent={this._renderLayout.bind(this)}
            onEndReached={({distanceFromEnd}) => this._onEndReached(distanceFromEnd)}
            onEndReachedThreshold={0.1} // 这里取值0.1（0~1之间不包括0和1），可以根据实际情况
        />;

**Comment by 2534290808** [comment]
马上进行处理

**Comment by 2534290808** [comment]
你好，请把{...props}作为ScrollView的属性，而不是作为LottieRefreshControl属性，请见最新Example

**Comment by geniu-vs** [comment]
感谢您的回复，我再试一下
