### ISSUE TITLE
FLatList卡顿问题

### ISSUE THREAD

**Issue by lhh-sofy** [react-native-studio/react-native-MJRefresh#20]
你好，用了这个组件之后，发现会卡顿，一顿一顿的。
我感觉你可以从 他这个RefreshControl组件中去重写一个。。不懂原生，不晓得好写不。。。

**Comment by 2534290808** [comment]
我这边用模拟器调试没有产生卡顿哎，能给些具体的代码信息吗？

**Comment by 2534290808** [comment]
或者你可以运行我的示例看看

**Comment by lhh-sofy** [comment]
我把我这边的代码截图发一下。我是在react-native-scrollable-tab-view 这个组件之后使用的FlatList
滚动时候，滚动条不顺滑。
<img width="591" alt="99e3e0c1-c6a1-4939-a10d-3682c4d6f3f7" src="https://user-images.githubusercontent.com/13582183/46589673-fcf0f380-cade-11e8-9500-95ead5ad0d76.png">

**Comment by 2534290808** [comment]
请问React Native的版本是多少啊？

**Comment by lhh-sofy** [comment]
不好意思哈，是0.57.1  HuaWeiRefreshControl这个是从你那边的git上下载的

**Comment by 2534290808** [comment]
这边我测试了一下，看不到你的那个效果，能发个视频给我吗？微信lmy234290808

**Comment by 2534290808** [comment]
解决办法，修改scrollable-tab-view中index.js文件，修改如下
第一：增加如下代码
<img width="817" alt="2018-10-08 4 47 23" src="https://user-images.githubusercontent.com/24295236/46600225-1c5a4180-cb1c-11e8-85b1-979d12edf852.png">
第二：修改Animated.ScrollView为AnimatedScrollView
<img width="883" alt="2018-10-08 5 09 50" src="https://user-images.githubusercontent.com/24295236/46600546-0a2cd300-cb1d-11e8-8078-bf33b21ef8ee.png">

**Comment by geniu-vs** [comment]
> 解决办法，修改scrollable-tab-view中index.js文件，修改如下
> 第一：增加如下代码
> <img alt="2018-10-08 4 47 23" width="817" src="https://user-images.githubusercontent.com/24295236/46600225-1c5a4180-cb1c-11e8-85b1-979d12edf852.png">
> 第二：修改Animated.ScrollView为AnimatedScrollView
> <img alt="2018-10-08 5 09 50" width="883" src="https://user-images.githubusercontent.com/24295236/46600546-0a2cd300-cb1d-11e8-8078-bf33b21ef8ee.png">

按这个方式改过了，但是每次左右滑动的时候，会自动触发点击事件，进入二级页面
