### ISSUE TITLE
CocoaPods管理第三方库的项目，导入此插件找不react相关头文件

### ISSUE THREAD

**Issue by anye931123** [react-native-studio/react-native-MJRefresh#23]
如题

**Comment by anye931123** [comment]
因为项目中灭有.podspec配置文件，如果ios代码使用了pod管理就会出现此类问题，还有如果原生ios使用了MJRefresh库将会与此插件的库冲突

**Comment by anye931123** [comment]
可否建个群讨论，我没做过ios开发，遇到问题很难解决

**Comment by 2534290808** [comment]
podfile文件可以发给我看看嘛

**Comment by anye931123** [comment]
source 'https://github.com/CocoaPods/Specs.git'                       #公有库地址

platform :ios, '9.0'

target 'xbxx' do
    ########私有库########
    pod 'JYBuglyManager','0.0.3'      #腾讯Bugly统计库组件库
    pod 'JYUMengManager','0.0.3'      #友盟统计组件库
    pod 'JYFaceIDManager','0.0.3'     #Face++组件库
    pod 'JYUMengShareManager','0.1.4' #友盟分享组件库
    pod 'JYThirdPartyManager','0.0.2' #第三方组件库
    pod 'JYMediator','0.0.2'          #中间服务层组件
    pod 'JYGDMapManager','0.0.2'      #第三方高德地图组件
    pod 'JYAESManager','0.0.2'        #加密解密管理者组件
    pod 'JYUnitTestManager','0.0.1'   #单元测试管理者组件

#    pod 'JYJPushManager'      #极光推送组件库

    pod 'YXKBaseModule','0.5.5'       #项目的基础模块组件组件
    pod 'YXKMacro','0.0.6'            #项目全局宏
    pod 'YXKHttpManager','0.4.4'      #项目网络请求库

    ########第三方库########
    pod 'Masonry','1.1.0'
    pod 'IQKeyboardManager','6.1.1'
    pod 'YYModel','1.0.4'
    pod 'MJRefresh','3.1.15.3'
    pod 'SSZipArchive','2.1.4'
    pod 'MBProgressHUD','1.1.0'
    pod 'AvoidCrash','2.5.2'
    pod 'UMCShare/Social/ReducedWeChat','6.9.4'
    pod 'UMCShare/Social/ReducedQQ','6.9.4'
    pod 'UMCShare/Social/ReducedSina','6.9.4'
    pod 'EZImageBrowserKit','0.0.2'

    pod 'AFNetworking','3.2.1'
    
    pod 'AMap3DMap','6.3.1'
    pod 'AMapFoundation','1.5.3'
    pod 'AMapLocation','2.6.0'

    pod 'AMapSearch','6.1.1'
    pod 'BGFMDB','2.0.12'
    pod 'Bugly','2.5.0'
    pod 'SDWebImage','4.4.2'
    pod 'UMCAnalytics','5.5.1'
    pod 'UMCCommon','1.5.2'
    pod 'UMCSecurityPlugins','1.0.6'
    pod 'BGFMDB','2.0.12'
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      # 'BatchedBridge',
      'Core',
      'CxxBridge', # 如果RN版本 >= 0.45则加入此行
      'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
      'RCTAnimation',
      'RCTPushNotification',
      'RCTLinkingIOS',
      'RCTBlob',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTSettings',
      'RCTVibration',
      'RCTCameraRoll'
      # Add any other subspecs you want to use in your project
    ]
    # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'react-native-video', :path => '../node_modules/react-native-video'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    pod 'lottie-ios', :path => '../node_modules/lottie-ios'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'JPushRN', :path => '../node_modules/jpush-react-native'
    pod 'JCoreRN', :path => '../node_modules/jcore-react-native'
    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'Picker', :path => '../node_modules/react-native-picker'

end

**Comment by 2534290808** [comment]
升级到最新版本在podfile中加上pod 'RCTMJRefreshHeader', :path => '../node_modules/react-native-mjrefresh'，执行pod install，然后试试
