### ISSUE TITLE
cocoapods管理问题，没有修复好，导入的库没有东西，报错

### ISSUE THREAD

**Issue by anye931123** [react-native-studio/react-native-MJRefresh#24]
<img width="297" alt="db3e18b7-169c-4de0-b711-7a6d06038846" src="https://user-images.githubusercontent.com/15995127/47058919-bcd5f300-d1f9-11e8-9d08-c09dc9c5ae92.png">

<img width="382" alt="9be15451-842e-4299-b970-84be0f4cb2ad" src="https://user-images.githubusercontent.com/15995127/47059169-ad0ade80-d1fa-11e8-9968-c06d510d6b39.png">

**Comment by 2534290808** [comment]
做了一些修改，更新到最新版本，再试试

**Comment by anye931123** [comment]
这次修改倒是能导进去，但是因为我们原生层也用到了MJRefresh库，跟这个库中的MJRefresh产生冲突了，所以还是报错找不到`#import <React/RCTView.h>`，但是我们原生开发将你的RCTMJRefreshHeader单独提出来，后编译通过没问题

**Comment by 2534290808** [comment]
重复导入应该删除一个就行吧

**Comment by anye931123** [comment]
删除原生依赖的MJRefresh库原生代码报错，原生依赖的MJRefresh版本为'3.1.15.3'

**Comment by 2534290808** [comment]
那你就单独提出RCTMJRefreshHeader吧

**Comment by anye931123** [comment]
嗯，提出来的没做任何修改可以支持上拉加载不知为啥，你的例子不支持

**Comment by 2534290808** [comment]
其实你竟然原生用了MJRefresh，我觉得就没有必要引用我库了，可以自己封装一下

**Comment by 2534290808** [comment]
这样更好

**Comment by anye931123** [comment]
我不会ios，我们原生端不会RN所有自己封装成本高，你的库能不能MJRefresh与RCTMJRefreshHeader分开导入，这样如果再有人遇到这种情况就不用我们这么麻烦了。

**Comment by 2534290808** [comment]
这个可能后续再分开吧
