### ISSUE TITLE
使用这个库之后，release版本手势冲突。

### ISSUE THREAD

**Issue by SurpassRabbit** [react-native-studio/react-native-MJRefresh#26]
重写flatList的renderScrollComponent之后，下拉动画出来了
但当快速向上，或者向下滚动时，会出现，第一个手势没结束，再去触发第二个手势，会让列表停下，需要再滚动一次

**Comment by 2534290808** [comment]
请问是和react-native-scrollable-tab-view一起使用导致吗？

**Comment by SurpassRabbit** [comment]
是的

**Comment by 2534290808** [comment]
可以看一下    #20
