### ISSUE TITLE
编译错误，错误截图如下

### ISSUE THREAD

**Issue by lhh-sofy** [react-native-studio/react-native-MJRefresh#30]
![wechatimg222](https://user-images.githubusercontent.com/13582183/48877824-fc6aad00-ee3f-11e8-9e6d-d37dd61d613a.jpeg)
错误原因：#import xxx.m之类的错误，改为.h。
错误文件：ios->RCTMJRefreshHeader->RCTMJRefreshHeader->RCTMJRefreshViewManager.m文件

**Comment by 2534290808** [comment]
感谢，很快修复

**Comment by 2534290808** [comment]
新版本已经修复，谢谢你的issue
