### ISSUE TITLE
你好  ios 8.0的版本  5s的手机   我们公司只有一个8.0的手机   有解决的方法吗？ 挺急的

### ISSUE THREAD

**Issue by zkkg2018** [react-native-studio/react-native-MJRefresh#35]
直接闪退 9.0-10.0的版本不知道

**Comment by 2534290808** [comment]
这个react-native github主页的描述

Supported target operating systems are >= Android 4.1 (API 16) and >= iOS 9.0. You may use Windows, macOS, or Linux as your development operating system, though building and running iOS apps is limited to macOS by default (tools like Expo can be used to get around this).

**Comment by zkkg2018** [comment]
Supported target operating systems are >= Android 4.1 (API 16) and >= iOS 9.0. You may use Windows, macOS, or Linux as your development operating system, though building and running iOS apps is limited to macOS by default (tools like Expo can be used to get around this). 说实话 你这个看不懂 没有办法解决吗？

**Comment by qxj006** [comment]
支持iOS9.0及以上
