### ISSUE TITLE
在rn 0.58.5版本中不能使用,报错如下:

### ISSUE THREAD

**Issue by lhh-sofy** [react-native-studio/react-native-MJRefresh#37]
error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Lists/MetroListView` from `/Users/hubin/Desktop/react-native/app/toutiao/node_modules/react-native-mjrefresh/MJMetroListView.js`: Module `react-native/Libraries/Lists/MetroListView` does not exist in the Haste module map

**Comment by hanwenbo** [comment]
你需要pod intall

**Comment by hanwenbo** [comment]
rn 0.58.6

**Comment by hanwenbo** [comment]
@lhh-sofy 你解决了吗

**Comment by hanwenbo** [comment]
https://github.com/facebook/react-native/commit/4a5221884f7dfd431840c09f860451739bf8a98f  我看了下5.8删除了这个，所以降级等着库升级吧

**Comment by 2534290808** [comment]
0.7.0版本已经修复该问题
