### ISSUE TITLE
内容还是滚动不了

### ISSUE THREAD

**Issue by RoarRain** [react-native-studio/react-native-MJRefresh#4]
![7 -10-2018 12-01-00](https://user-images.githubusercontent.com/10494442/42488665-333b0fbc-8439-11e8-8951-ef53843059df.gif)

'''
<View style={styles.container}>
                <ScrollView
                    contentContainerStyle={{ paddingBottom: 100}}
                    refreshControl={
                               <MJRefresh
                                  ref={ref=>this._mjrefresh = ref}
                                  onRefresh={
                                  ()=>{
                                      this.setState({
                                          text:'正在刷新'
                                      })
                                      console.log('onRefresh')
                                      setTimeout(()=>{
                                          this._mjrefresh && this._mjrefresh.finishRefresh();
                                      },1000)
                                  }
                                  }
                                  onRefreshIdle={()=>console.log('onRefreshIdle')}
                                  onReleaseToRefresh={()=>{
                                      this.setState({
                                          text:'释放刷新'
                                      })
                                  }}
                                  onPulling={e=>{
                                      if(e.nativeEvent.percent<0.1){
                                          this.setState({
                                              text:'下拉刷新'
                                          })
                                      }
                                  }}
                              >
                                <View style={{height:100,backgroundColor:'red',
                                    justifyContent:'center',
                                    alignItems:'center',flexDirection:'row'
                                }}>
                                  <Text>{this.state.text}</Text>
                                </View>
                              </MJRefresh>
                    }
                    ref={e => this.scrollView = e}
                    style={{flex:1}}
                    scrollEnabled={this.state.scrollEnabled} >

                    <View
                        style={{
                            height: 200,
                            backgroundColor: 'green',
                            width: Metrics.screenWidth
                        }}
                    />
                    <View
                        style={{
                            height: 200,
                            backgroundColor: 'blue'
                        }}
                    />
                    <View
                        style={{
                            height: 200,
                            backgroundColor: 'yellow'
                        }}
                    />
                    <View
                        style={{
                            height: 200,
                            backgroundColor: 'blue'
                        }}
                    />
                    <View
                        style={{
                            height: 200,
                            backgroundColor: 'green'
                        }}
                    />
                </ScrollView>
</View>

container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
}

**Comment by 2534290808** [comment]
我这边是可以的，已经不需要修改RN官方的ScrollView了，可插件里重新引入ScrollView
import {ScrollView} from 'react-native-mjrefresh'
请重新读README.md

**Comment by 2534290808** [comment]
重新运行yarn add react-native-mjrefresh，最新版本0.5.3，再试一下，谢谢
