### ISSUE TITLE
React Native 0.48有问题 没有RCTLayout这个文件

### ISSUE THREAD

**Issue by RoarRain** [react-native-studio/react-native-MJRefresh#5]
<img width="595" alt="qq20180712-095803 2x" src="https://user-images.githubusercontent.com/10494442/42609160-b744e21c-85bd-11e8-8898-e4a01ab6893e.png">

0.48官方的RCTScrollContentShadowView.m文件是这样

`
#import "RCTScrollContentShadowView.h"

#import <yoga/Yoga.h>

#import "RCTUtils.h"

@interface RCTShadowView () {
  // This will be removed after t15757916, which will remove
  // side-effects from `setFrame:` method.
  @public CGRect _frame;
}
@end

@implementation RCTScrollContentShadowView

- (void)applyLayoutNode:(YGNodeRef)node
      viewsWithNewFrame:(NSMutableSet<RCTShadowView *> *)viewsWithNewFrame
       absolutePosition:(CGPoint)absolutePosition
{
  // Call super method if LTR layout is enforced.
  if (self.effectiveLayoutDirection == UIUserInterfaceLayoutDirectionLeftToRight) {
    [super applyLayoutNode:node
         viewsWithNewFrame:viewsWithNewFrame
          absolutePosition:absolutePosition];
    return;
  }

  // Motivation:
  // Yoga place `contentView` on the right side of `scrollView` when RTL layout is enfoced.
  // That breaks everything; it is completly pointless to (re)position `contentView`
  // because it is `contentView`'s job. So, we work around it here.

  // Step 1. Compensate `absolutePosition` change.
  CGFloat xCompensation = YGNodeLayoutGetRight(node) - YGNodeLayoutGetLeft(node);
  absolutePosition.x += xCompensation;

  // Step 2. Call super method.
  [super applyLayoutNode:node
       viewsWithNewFrame:viewsWithNewFrame
        absolutePosition:absolutePosition];

  // Step 3. Reset the position.
  _frame.origin.x = RCTRoundPixelValue(YGNodeLayoutGetRight(node));
}

@end
`

**Comment by 2534290808** [comment]
你好，请使用react-native-mjrefresh-lower，README.md已经更新，感谢你的issue

**Comment by RoarRain** [comment]
好的 谢谢更新
