### ISSUE TITLE
我们在 ios 项目中使用框架会出现 错误： Cannot find RCTScrollView with tag #282 希望能提供一些帮助

### ISSUE THREAD

**Issue by Season02** [react-native-studio/react-native-MJRefresh#8]
我们只做了 link 操作。

**Comment by 2534290808** [comment]
请问你的rn版本是多少？

**Comment by yhyfms** [comment]
@2534290808 我们用的是0.49.0

**Comment by 2534290808** [comment]
你好，我这边是可以的，0.54以下请使用react-native-mjrefresh-lower

**Comment by 2534290808** [comment]
经过检查，是ListView这段代码的问题：
将
var RCTScrollViewManager = require('NativeModules').ScrollViewManager;
改为
var RCTScrollViewManager = require('NativeModules').MJScrollViewManager;
即可
如果使用FlatList则不会出现此错误
该问题会一直issue会一直打开，直到有合适的方法解决为止

**Comment by yhyfms** [comment]
@2534290808 我们用的react-native-mjrefresh-lower，然后执行react-native link，但在运行时报了上边的错。在ios原生里不用做任何操作吗，不用做一些手动配置吗？

**Comment by gukeming** [comment]
@2534290808 是不是使用ListView只能去改RN源码才行啊

**Comment by 2534290808** [comment]
已经修复，可从库中引入ListView，详情请见ListViewExample
