### ISSUE TITLE
求大佬更新！！

### ISSUE THREAD

**Issue by chj-damon** [react-native-studio/react-native-MJRefresh#83]
求大佬适配一波最新的RN和MJRefresh

**Comment by andyDY** [comment]
+1

**Comment by arafat813** [comment]
有找到合适的库么

**Comment by chj-damon** [comment]
试试： https://github.com/sdcxtech/react-native-troika/blob/master/packages/pull-to-refresh/README.md

**Comment by arafat813** [comment]
这个库 我试过，内容含有旧的安卓api，安卓端用不了， 自己用reanimated 搞了一个 感觉没有那么流畅

**Comment by chj-damon** [comment]
我用得好好的。0.72都能用，很舒服。

**Comment by arafat813** [comment]
0.72可以么。我用的是 0.75

**Comment by chj-damon** [comment]
0.75就别想了，确实不支持

**Comment by arafat813** [comment]
我是第一次用RN来着，我看官方文档说0.75以前的版本都不维护了， 还用以前的没关系么
